/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_webrsync_sftp_SftpFileAttributes */

#ifndef _Included_com_github_webrsync_sftp_SftpFileAttributes
#define _Included_com_github_webrsync_sftp_SftpFileAttributes
#ifdef __cplusplus
extern "C" {
#endif
#undef com_github_webrsync_sftp_SftpFileAttributes_S_IFMT
#define com_github_webrsync_sftp_SftpFileAttributes_S_IFMT 61440L
#undef com_github_webrsync_sftp_SftpFileAttributes_S_IRWXU
#define com_github_webrsync_sftp_SftpFileAttributes_S_IRWXU 448L
#undef com_github_webrsync_sftp_SftpFileAttributes_S_IRWXG
#define com_github_webrsync_sftp_SftpFileAttributes_S_IRWXG 56L
#undef com_github_webrsync_sftp_SftpFileAttributes_S_IRWXO
#define com_github_webrsync_sftp_SftpFileAttributes_S_IRWXO 7L
/*
 * Class:     com_github_webrsync_sftp_SftpFileAttributes
 * Method:    stat
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_github_webrsync_sftp_SftpFileAttributes_stat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_github_webrsync_sftp_SftpFileAttributes
 * Method:    getLocalDomainName
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_webrsync_sftp_SftpFileAttributes_getLocalDomainName
  (JNIEnv *, jobject);

/*
 * Class:     com_github_webrsync_sftp_SftpFileAttributes
 * Method:    getOwnerName
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_github_webrsync_sftp_SftpFileAttributes_getOwnerName
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
